Add support for Apple Pay in Popup
tubiz/woo-paystack pull request #112
Opened 2024-11-25 12:10 UTC by lukman-paystack

# Update to use Paystack Checkout API

- Updated payment flow from `newTransaction()` to new `checkout()` method
- Fixed merchant logo sizing issues (48px height)

2024-11-25 12:14 UTC, lukman-paystack commented
Hi @tubiz, could you please help review and merge this PR? Thank you!

2024-12-16 14:14 UTC, tubiz commented on assets/js/paystack.js
> +	$('head').append('<style>.merchant-logo img, img.merchant-logo { max-height: 30px !important; width: auto; }</style>');
Can this be removed? I guess this is overriding a global style applied by Paystack?

2024-12-16 14:15 UTC, tubiz requested changes

2024-12-16 14:15 UTC, tubiz commented on assets/js/paystack.js
> +				console.log('Transaction:', transaction);
Remove logging to the console.

2024-12-16 14:15 UTC, tubiz commented on assets/js/paystack.js
> +				console.error('Paystack checkout error:', error);
Remove logging to the console.

2024-12-16 14:15 UTC, tubiz commented on assets/js/paystack.js
> +			console.error('Paystack checkout error:', error);
Remove logging to the console.

2026-04-30 13:45 UTC, closed without merging